.asf.yaml, .github/workflows/jekyll.yml, README.md, _config.yml
Signed-off-by: tison <wander4096@gmail.com>
=> ci: add jekyll pages actions

_data/project.yml, _includes/themes/apache/_navigation.html, index.md
=> Add incubating in the headline

community/how-to-release.md, community/how-to-verify.md, community/how-to-vote-a-committer-pmc.md, community/index.md
Add below docs in community:
- How to vote a committer/pmc
- How to release
- How to verify
=> Add some how to docs to community

community/how-to-release.md, docusaurus.config.js, download/index.md
- Modified some contents according to our release process
- Add the download page
=> Update how-to-release and add download page

docs/01-supported-commands.md
GETDEL command was introduced by this PR: https://github.com/apache/incubator-kvrocks/pull/771
=> Add the new command getdel to supported commands

docs/01-supported-commands.md
Add stream commands which were implemented in: https://github.com/apache/incubator-kvrocks/pull/745
=> Add stream commands to supported commands doc

docs/01-supported-commands.md
[Issue Link](https://github.com/apache/incubator-kvrocks/issues/894)
=> Add Hrange command

docs/01-supported-commands.md
[Issue Link.](https://github.com/apache/incubator-kvrocks/issues/874)
=> Add Disk command

docs/02-server-installation.md
So the new user could easily understand before read kvrocks.conf
=> Add default data directory volume mount for using docker

community/committers.md
=> Add the committers page in community

docs/01-supported-commands.md
=> Fix function command table in supported commands

docs/supported-commands.md
refer to https://github.com/apache/incubator-kvrocks/pull/1120
=> Add `hrangebylex` to supported commands

community/contributing.md, docs/cluster.md, package.json, sidebarsCommunity.js, yarn.lock
We add the contributing page named "How to Contribute" in the Community collection.
=> Add the contributing page in community

docs/supported-commands.md
Refer to https://redis.io/commands/unlink/.
=> Move unlink from string to key category

community/create-a-release.md, docusaurus.config.js
=> docs: More on Docker images

docs/supported-commands.md
The watch/unwatch command has been supported in PR https://github.com/apache/incubator-kvrocks/pull/1279 by @PragmaTwice, so mark them as supported commands here.
=> Mark the watch/unwatch command as supported commands

docusaurus.config.js, package.json, yarn.lock
Can enlarge the image size when clicking, like below:
=> Support image zoom when clicking

docs/supported-commands.md
SUBSTR was added in apache/incubator-kvrocks#1347
=> Add SUBSTR in supported-commands list

community/data-structure-on-rocksdb.md
=> Add the key encoding description

docusaurus.config.js
Related link: https://whimsy.apache.org/pods/project/kvrocks
=> Update the privacy link according to the website checker

community/vote-a-core-developer.md
=> Add nominate new committer section to the committer guide

community/vote-a-core-developer.md
Change the keyword from PMC to PPMC(Podling PMC)
=> Change the PMC to PPMC

docs/info-sections.md
This was added in apache/incubator-kvrocks#1379
=> Add cluster section into the info command

src/pages/index.module.css, src/pages/index.tsx
The hero.png  has been moved to a position further to the left to make page structure look more reasonable.
before:
after:
Besides, The font size will be self-adjusted when browser screen width is changed.
The  screen width becomes smaller, the font size is adjusted to be smaller too.
=> Auto recalculate positions according to the page size

community/data-structure-on-rocksdb.md
=> Add more concrete key encoding

docs/faq.md, sidebars.js
Add a page to collect frequently asked questions from the community.
=> Add FAQ page

README.md
Minor text changes to improve readability.
=> Update README.md - minor text changes

docs/faq.md
Minor text changes to improve readability
=> Update faq.md - minor text changes

docs/getting-started.md
Minor text edits to improve readability
=> Update getting-started.md - minor text edits

docs/supported-commands.md
At https://github.com/apache/incubator-kvrocks/pull/1482 we add the support of the ZRANGESTORE command
=> add zrangestore to supported-commands.md

community/vote-a-core-developer.md
Update the new committer invitation email template according to https://lists.apache.org/thread/fjz9s160rxd7rxg8l5th0s0sdz425syj
=> Update new committer invitation email template

docs/supported-commands.md
The all related commands from sets in redis are supported now.
=> add the sintercard command to support-commands.md

blog/2022-11-20-go-redis-kvrocks-opentelemetry/index.md
I've updated some information in the post and fixed broken/redirecting links.
=> chore: update go-redis and kvrocks post

community/index.md, community/vote-a-core-developer.md, docusaurus.config.js
- Update PPMC to PMC after graduation
- Remove incubator keyword
=> Update the vote a core developer: PPMC => PMC

community/create-a-release.md, community/verify-a-release-candidate.md
Refactor the release guide after #114
=> Refactor the release and verify guide after graudation

docs/supported-commands.md
Add some new commands for zsets, including zmpop, bzmpop, bzpopmin and bzpopmax.
=> Yangsx 1 add command

docs/faq.md
Add the scan-compatible issue to the FAQs after PR https://github.com/apache/kvrocks/pull/1489.
=> Add the scan compatible case to the FAQs

blog/2023-07-01-kvrocks-graduated-as-tlp/index.md
Apply suggestions after wrongly merge the PR: #120
=> Apply suggestions from tison

src/pages/users.mdx
Same as README in apache/kvrocks.
=> Add URL for the user finding issue in the User page

docs/supported-commands.md
Added georadius_ro and georadiusbymember_ro, the rest of the diff is indentation.
=> Add missing GEO commands

docs/supported-commands.md
=> Add zunion to supported commands

docs/getting-started.md
refer to README in apache/kvrocks.
=> Update commands in getting-start

docs/info-sections.md
The INFO page kind of outupdates over time, this PR
reflashes it based on the latest unstable branch.
=> Refresh the INFO page to add missing fields

docs/supported-commands.md
=> Adds new commands GEOSEARCH and GEOSEARCHSTORE

src/components/Releases/index.tsx
The vote result thread: https://lists.apache.org/thread/1skronrd93tk5o3ycshhm4v5lw4469oo
=> Add the new release 2.5.1

docs/kvrocks2redis.md, sidebars.js
=> Add new doc: kvrocks2redis

docs/getting-started.md
Follow https://github.com/apache/kvrocks/blob/unstable/.github/workflows/kvrocks.yaml.
=> Add SUSE and archlinux setup in getting-started.md

docs/supported-commands.md
Added in https://github.com/apache/kvrocks/pull/1681
=> Add LPOS to supported commands

docs/supported-commands.md
related PR: https://github.com/apache/kvrocks/pull/1684
=> Add the restore command

docs/supported-commands.md
Scanned cmd_server.cc and found that these commands are missing
=> Refresh server supported-commands table

docs/supported-commands.md
Added in https://github.com/apache/kvrocks/pull/1723
=> Add MOVE command

docusaurus.config.js
Refer to https://github.com/apache/kvrocks/issues/1742.
=> Add statement of the Redis trademark

docs/supported-commands.md
Refer https://github.com/apache/kvrocks/pull/1737
=> Add LMPOP command to supported commands

docs/supported-commands.md
refer to https://github.com/apache/kvrocks/issues/1696 and https://github.com/apache/kvrocks/pull/1774
=> Add bloomfilter and blmpop in supported-commands.md

.github/workflows/deploy.yml
"Last updated on ..." need more commit information.
=> Make last-updated more accurate

src/components/Releases/index.tsx
refer to https://lists.apache.org/thread/r1kqbh69njmw5kp7o0sk42f4lo0221dy
=> Add release 2.6.0

docusaurus.config.js
=> Add controller to footer

docs/supported-commands.md
=> Add function commands to supported-commands.md

docs/supported-commands.md
refer to https://github.com/apache/kvrocks/pull/1791
=> Add FCALL_RO to supported-commands.md

docs/supported-commands.md
refer: https://github.com/apache/kvrocks/pull/1798
=> Add rdb load command

docs/supported-commands.md
Refer to https://github.com/apache/kvrocks/issues/1805.
=> Add JSON commands to supported-commands.md

docs/supported-commands.md
Refer to https://github.com/apache/kvrocks/pull/1847.
=> Add JSON.TYPE to supported-commands.md

docs/supported-commands.md
- change command name to uppercase
- add JSON.CLEAR and JSON.ARRLEN
=> Add more JSON commands & refactor command lists

src/components/Releases/index.tsx
The release 2.7.0 vote result: https://lists.apache.org/thread/pr4jo4khb6yyh7bmym9jmfbwnzmdb34m
=> Add the release 2.7.0

docs/supported-commands.md
I added Since version for each command. 
and fix doc mistake:
1. command -> COMMAND 
4. GETSEARCHSTORE -> GEOSEARCHSTORE
5. BF.MEXIST ->  BF.MEXISTS
please check~
=> Add the since version column for supported commands

docs/supported-commands.md
Refer: https://github.com/apache/kvrocks/pull/1990
=> Add new command BITFIELD_RO

docs/supported-commands.md
refer: https://github.com/apache/kvrocks/pull/1992
=> Add new command ZINTER and ZINTERCARD

docs/supported-commands.md
Refer: https://github.com/apache/kvrocks/pull/2003
=> Add new command: ssubscribe and sunsubscribe

src/components/Committers/index.tsx
=> Add new committers

docs/supported-commands.md
=> Update supported-commands.md for 2.8.0

src/components/Releases/index.tsx
The release 2.8.0 vote result: https://lists.apache.org/thread/y73xlngpq08k83fwvoyffttwzg78dnqy
=> Add the release 2.8.0

docs/supported-commands.md
Do we need to alphabetize these commands?
=> Add new command: LCS

docs/supported-commands.md
=> Add newly-supported commands in supported-commands.md

community/vote-a-core-developer.md
looks better and easy to understand
=> replace XXXXXX with descriptive placeholders

docs/supported-commands.md
=> Add search commands to supported-commands page

docs/supported-commands.md
=> Add FT.EXPLAIN to supported-commands.md

docs/supported-commands.md
Refer to https://github.com/apache/kvrocks/commit/f03d48caab79aba468957ccc782e47989960e609
=> Add XAUTOCLAIM to supported commands

src/components/Releases/index.tsx
See https://lists.apache.org/thread/bz6l59c56tjpp6pkfqcxq61rprxnr3t8
=> Add 2.9.0 to download page

docs/supported-commands.md
https://github.com/apache/kvrocks/commit/68523ac35dcb2d712dfac363c4cabe774ff927f6
=> Add XPENDING to supported-commands.md

docs/supported-commands.md
refer: https://github.com/apache/kvrocks/pull/2390
=> Add new command JSON.RESP

sidebarsDownload.js, src/components/Releases/kvrocks-controller.tsx
=> Add Kvrocks Controller 1.0.0 to the download page

docs/supported-commands.md
refer to https://github.com/apache/kvrocks/commit/727bec2e69958a170fc94c4ffec77e07ced25fce
=> Add HLL commands to supported-commands.md

community/kvrocks-search-index-encoding.md, sidebarsCommunity.js
New page to describe index encoding format of Kvrocks Search.
=> Add a new page for search encoding

docs/supported-commands.md
refer to https://github.com/apache/kvrocks/pull/2457
=> Add PFMERGE to supported-commands.md

community/kvrocks-search-index-encoding.md
Refer to https://github.com/apache/kvrocks/issues/2426
=> Update KVrocks search index encoding documentation

docs/getting-started.md
=> Remove old version in getting started

docs/supported-commands.md
- add FT.TAGVALS to supported-commands.md
- update 'since version' of commands
=> Add FT.TAGVALS to supported-commands.md

src/components/Releases/index.tsx
=> Add the new release v2.10.0

src/components/Releases/index.tsx
Vote thread: https://lists.apache.org/thread/h291d7333kh5yh1cg0sb3253vm3hs1mf
=> Release 2.10.1

docs/kvrocks-search.md, sidebars.js
Although it's not a comprehensive document, but it's required for users to understand how to use Kvrocks Search.
We'll keep to make it more complete.
=> Add user documentation for Kvrocks Search

download/third-party-packages.md
Refer to https://anaconda.org/conda-forge/kvrocks.
=> Add the conda-forge kvrocks package

docs/supported-commands.md
See https://github.com/apache/kvrocks/pull/2678.
=> Add REPLICAOF to supported-commands.md

src/components/Releases/index.tsx
See https://lists.apache.org/thread/qykqv0g4hz7tykbc2oktvv53g9py1don.
=> Release 2.11.0

docs/supported-commands.md
some unstable should be replaced with 2.11.0 since it's released.
=> Update version info in supported-commands.md

src/components/Releases/index.tsx, src/components/Releases/kvrocks-controller.tsx
The release tarball should be `dyn/closer.lua`.
=> Change the tarball download url to `dyn/closer.lua`

src/components/Releases/kvrocks-controller.tsx
See https://lists.apache.org/thread/5rhx05wg8dyoowgjltjkzqmymgfoolon
=> Add new controller release 1.1.0

docs/supported-commands.md
Refer to https://github.com/apache/kvrocks/commit/64fbd28f4f49123a64e8f464d5039df21db3110e and https://github.com/apache/kvrocks/commit/f7c5688fe4030f148195e7043208ae659df48ea7
=> Add TDIGEST to supported-commands.md

docs/supported-commands.md
=> Add comments for some commands in supported-commands.md

docs/supported-commands.md
Referencing: https://github.com/apache/kvrocks/issues/2817
This PR adds documentation for the ``LASTSAVE [format]`` command in the Server Commands section of the Supported Commands page in KVrocks.
=> doc(server): Added documentation for LASTSAVE [format] command.

download/kvrocks-controller.mdx
=> Add docker image description to kvrocks-controller download page

docs/supported-commands.md
=> Fix table format of supported-commands.md

src/components/Releases/index.tsx
Vote result thread: https://lists.apache.org/thread/s7w50p6xo1x9t8d408wfb33oclwsdzjv
=> Add new release 2.12.0

src/components/Committers/index.tsx
=> Update committer list

docs/supported-commands.md
this PR intents to resolve https://github.com/apache/kvrocks/issues/2587
references:
[SCRIPT](https://redis.io/docs/latest/commands/?group=scripting)
[FUNCTION](https://redis.io/docs/latest/commands/?group=scripting)
=> Adding Script and Function subcommands

src/components/Releases/index.tsx
See https://lists.apache.org/thread/bbfy2tlwc4800f9llhn59srv03cmqpyb
=> Release 2.12.1

docs/supported-commands.md
Referencing: https://github.com/apache/kvrocks/pull/2849
=> Add docs for TDIGEST.QUANTILE command

community/vote-a-core-developer.md
The Whimsy now supports sending out the NOTICE email to board while newly adding a PMC member.
=> Change the newly add a PMC member section

docs/supported-commands.md
see https://github.com/apache/kvrocks/pull/3007
=> Add new command: KPROFILE

community/kvrocks-search-index-encoding.md
=> Update the status of Kvrocks Search in encoding docs

docs/supported-commands.md
=> Add FLUSH* to supported-commands.md

docs/kvrocks-search.md
=> Add DIALECT 2 support into kvrocks-search.md

docs/supported-commands.md
=> Add TDIGEST.MERGE into supported-commands.md

src/components/Releases/index.tsx
None
Add new release [2.13.0](https://github.com/apache/kvrocks/releases/tag/v2.13.0) documentation.
=> chore(release): publish release 2.13.0

docs/supported-commands.md
=> Update supported commands for v2.13.0

community/create-a-release.md
None
Update the release process documentation to match the latest process.
=> doc: update release process documentation

docs/supported-commands.md
=> Add FUNCTION FLUSH into supported-commands.md

docs/faq.md
related to：https://github.com/apache/kvrocks/pull/3125
=> Add a hint to the build command for MacOS

docs/supported-commands.md
Refer to https://github.com/apache/kvrocks/commit/d6bf6846d1954337dab28948521215765bda5b54.
=> Add TS.INFO to supported commands

docs/supported-commands.md
=> Update documentation for db size and SELECT command

src/components/Committers/index.tsx
@Jitmisra added to committer list. Congrats🥳
BTW @Jitmisra, you can follow https://infra.apache.org/new-committers-guide.html to set up your new email address and join the apache GitHub organization : )
After joining the org, you'll have commit access of Kvrocks repos.
=> Add Agnik Misra to committers

docs/supported-commands.md
Refer to https://github.com/apache/kvrocks/issues/3048.
=> Add new commands TS.CREATERULE, TS.MGET, and TS.MRANGE

community/data-structure-on-rocksdb.md
Refer to https://github.com/apache/kvrocks/issues/3048.
=> Add docs for Timeseries data structure

src/components/Committers/index.tsx
Refer to https://lists.apache.org/thread/jznl4t6x5y5zn0hfmn6qt1by0lqsfwgt.
=> Add Rongxing Xiao to committers list
