apache/kvrocks-website

.asf.yaml

We protect main branch from force push by modifying .asf.yaml, refer to https://cwiki.apache.org/confluence/display/INFRA/Git+-+.asf.yaml+features#Git.asf.yamlfeatures-Branchprotection.

Protect main branch from force push

---

docs/cluster.md
docs/namespace.md
docs/replication.md
src/components/HomepageFeatures/index.tsx

Here's the changed part of the PR:
- Corrected CLUSTERX commands to CLUSTERX
- Use `` to wrap commands
- Fix typo

Some cleanups in docs

---

docs/supported-commands.md

This PR also change `was extreme long` to `is extremely long` to be precise.

Fix wrong documentation

---

docusaurus.config.js

Footer is normally in dark color mode. Revert related changes in #64.
Dark (proposed):
Light (current):

fix: dark footer

---

blog/2021-11-07-how-to-implement-bitmap-on-rocksdb/index.md

Summary of Changes:
1. remove `ZWSP` from `WiscKey: Separating Keys from Values in SSD-conscious Storage`
2. add a space between to128, change `to128` to `to 128`
3. remove a extra space
4. add a period, consistent with the above
5. fix dead `redis_bitmap.cc` github link

cleanups in bitmap blog article

---

src/components/HomepageFeatures/index.tsx

The text boxes and pie charts in the design draft are only used for placeholder purposes. This image containing Nebula-related text should not be displayed on the homepage.

Remove the placeholder Images

---

community/vote-a-core-developer.md

NOTICE should be send to private@i.a.o instead of board@a.o

community: NOTICE should be sent to private@i.a.o

---

src/cdn.ts

Fix warning reports by Apache Podling Website Checker: https://whimsy.apache.org/pods/project/kvrocks
Those CDN links were introduced in PR #85

Remove the CDN path to fulfill apache website compliance

---

community/contributing.md

This closes https://github.com/apache/incubator-kvrocks/issues/1450.
For reviewing, I suggest you just open the [preview page](https://github.com/tisonkun/incubator-kvrocks-website/blob/doc-go-test/community/contributing.md) and review the final result.

docs: refactor contributing guide and add how to run a single test guide

---

community/data-structure-on-rocksdb.md

It's sourced from https://github.com/apache/incubator-kvrocks/blob/1dc5e9bb861ccc155996a1e5402553ca509da9d5/src/storage/redis_metadata.cc#L80-L105.

User Key Encoding should use 8 bytes for versions.

---

download/index.mdx
src/components/Releases/index.tsx

As the title mentioned, we move the resource after graduation, so need to fix the old download links.

Fix the download links after graduation

---

community/index.md

Currently using `podling=kvrocks` will show empty.

Update people link with project=kvrocks

---

docs/supported-commands.md

Clion report this warning: Table is not correctly formatted.
Re-format it to get rid of this annoying warning (although
clion is not a professional markdown editor).

Re-format the supported-commands markdown tables

---

community/create-a-release.md

Refer to https://github.com/apache/kvrocks/discussions/1540.
cc @apache/kvrocks-committers

Add the preparation section in create-a-release.md

---

community/data-structure-on-rocksdb.md

This explanation is incorrect. The metadata key and sub key of the hash type are in the same column families.
I remove it to avoid misunderstandings.

Remove the potentially misleading content in data-structure-on-rocksdb.md.

---

docs/supported-commands.md

`Set` command supported `KEEPTTL` and `GET` options since next version.
We can merge this PR after kvrocks 2.8 release.
Refer: https://github.com/apache/kvrocks/pull/1935

Update `Set` command desc

---

community/contributing.md
community/create-a-release.md
community/data-structure-on-rocksdb.md
community/index.md
community/vote-a-core-developer.md
docs/backup.md
docs/cluster.md
docs/faq.md
docs/getting-started.md
docs/info-sections.md
docs/kvrocks-exporter.md
docs/kvrocks2redis.md
docs/namespace.md
docusaurus.config.js
download/index.mdx
download/third-party-packages.md

According to https://www.apache.org/foundation/marks/guide:
> The first and most prominent mentions must use the full form: "Apache Hadoop®" of the name for any individual usage (webpage, handout, slides, etc.). Later in each specific document you may use the bare form of the name.

chore: use full form name when necessary

---

community/create-a-kvrocks-controller-release.md
community/verify-a-release-candidate.md
download/kvrocks-controller.mdx
sidebarsCommunity.js
src/components/Releases/kvrocks-controller.tsx

Add the release doc for the Kvrocks controller

---

community/index.md

Refer to https://lists.apache.org/thread/zpmynvxksbg32g1g2jnxnmydmp33f78g.
Currently we don't delete the Slack channel since the Zulip channel is still under discussion and construction.

Add zulip to community page

---

community/index.md

Since the Zulip migration is almost done.

Remove slack from community page

---

README.md
community/data-structure-on-rocksdb.md
docs/supported-commands.md

Close https://github.com/apache/kvrocks/issues/2813
- Add TDigest encoding internal details
- Update supported command list

doc(tdigest): add tdigest encoding details for documentation.

---

docusaurus.config.js
src/components/HomepageFeatures/index.tsx
src/components/HomepageFeatures/styles.module.css
src/css/custom.css
src/pages/index.module.css
src/pages/index.tsx
tsconfig.json

This pull request contains several modifications to enhance the dark mode support and the visual coherence of the website. The most significant changes are to allow the color mode switch, updating dark mode styles, and introducing new CSS variables for color tuning.
Enhancements to dark mode support:
* [`docusaurus.config.js`](diffhunk://#diff-a038096cbdea434999e1dce5ab497212f1fe18204dde1a027ce3bdd663261a2aL70-R71): Enabled the color mode switch and added support for respecting the user's preferred color scheme.
* [`src/css/custom.css`](diffhunk://#diff-44813f307e729042af7e70beff6f32ea63a7941bc100043a49e84d229ea2570fR10-R37): Added dark mode overrides for primary colors, background colors, and other UI elements.
Updates to component styles:
* …

Add Dark Mode Support 

---

docs/supported-commands.md

this PR intents to resolve [#2587](https://github.com/apache/kvrocks/issues/2587)
first commit adds subcommands for Bitmap group: `BITFIELD` and `BITFIELD_RO`.
thus covering one group each commit.
references:
1. [BITFIELD](https://redis.io/docs/latest/commands/bitfield/)
2. [BITFIELD_RO](https://redis.io/docs/latest/commands/bitfield_ro/)

Adding Supported Subcommands to Docs

---

docs/supported-commands.md

this PR intents to resolve https://github.com/apache/kvrocks/issues/2587
Given the colossal list of subcommands, PRs are divided in redis groups.
references:
1. [OBJECT](https://redis.io/docs/latest/commands/?group=generic)

Add object command

---

docs/supported-commands.md

this PR intents to resolve https://github.com/apache/kvrocks/issues/2587
Given the colossal list of subcommands, dividing PRs in redis groups.
Have also fixed table formats for server subcommands i added earlier.
references:
[SUBLOG](https://redis.io/docs/latest/commands/?group=server)
[COMMAND](https://redis.io/docs/latest/commands/?group=server)

Adding server subcommands slowlog and command with refactoring
